env:
  TZ: Asia/Jakarta
  USER_NAME: ENCRYPTED[63ff776b9902b2dd153fe9503ba70a9abacd0d192335e8c3b3d1a0cd1a586c5aa0b8c7a7a921e359ba866c9a3ecff795]
  USER_EMAIL: ENCRYPTED[e6311b58e2cbf1ec595db1ec83ec9cdad1f34a231e87402d758af8115588ca8408653f26385a5e75b47f38ccbb8a5747]
  GITHUB_TOKEN: ENCRYPTED[fb6c50d6b1030aa42a3fd0a3d6d379eb4131c49e61e04726f10de750f3e615c6f4203afa002301593b2855b03f0f2b95]
  FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
  FOX_SYNC_BRANCH: 12.1
  KERNEL_TREE:
  KERNEL_BRANCH:
  KERNEL_PATH:
  DEVICE_TREE: https://github.com/UntuKemeng/ORF_device_vivo_1938.git
  DEVICE_TREE_BRANCH: 12.1
  DEVICE_PATH: device/vivo/1938
  DEVICE_NAME: 1938
  BUILD_TARGET: recovery
  COMMON_TREE:
  COMMON_BRANCH:
  COMMON_PATH:
  MAINTAINER_URL: https://i.ibb.co.com/8gyjXq06/maintainer.png
  GH_RELEASE: true
  TG_CHAT_ID: ENCRYPTED[dbe17326a9269b441f9b84e8db03689a959d4413f6d1e217737ae8afbab14287b1a8285303c5e94bc37b8a92de22265c]
  TG_TOKEN: ENCRYPTED[7df5ff09770f675c1d6dbee3c406d8abe5d91c5f9ec38561ba92d3990e3db4e41e0baac309d3004ea59092c2cf9192fb]
  CONFIG: config.sh

container:
  image: mhmmdfdlyas/dockerfile:r-ubuntu
  cpu: 8
  memory: 32G

cloning_task:
  name: 🦊 Orangefox
  timeout_in: 120m
  sync_script:
    - source "${CONFIG}"
    - mkdir -p "${CIRRUS_WORKING_DIR}"/Orangefox
    - git config --global user.name "${USER_NAME}"
    - git config --global user.email "${USER_EMAIL}"
    - echo "${GITHUB_TOKEN}" >> ikitoken.txt
    - unset GITHUB_TOKEN
    - gh auth login --with-token < ikitoken.txt
    - git clone --single-branch "${FOX_SYNC}" "${CIRRUS_WORKING_DIR}"/Orangefox/sync --depth=1
    - cd "${CIRRUS_WORKING_DIR}"/Orangefox/sync
    - ./orangefox_sync.sh --branch "${FOX_SYNC_BRANCH}" --path "${CIRRUS_WORKING_DIR}"/Orangefox/fox_"${FOX_SYNC_BRANCH}"
    - if [[ ! -d bootable/recovery/gui/theme ]]; then
          echo -e ${cya} "Adding Theme..."
          git clone https://gitlab.com/OrangeFox/misc/theme.git bootable/recovery/gui/theme
      fi
    - if [[ ! -d external/nano ]]; then
          echo -e ${cya} "Adding Nano Library..."
          git clone https://github.com/LineageOS/android_external_nano -b lineage-19.1 external/nano
      fi
    - if [[ ! -d external/libncurses ]]; then
          echo -e ${cya} "Adding libncurses Library..."
          git clone https://github.com/LineageOS/android_external_libncurses -b lineage-19.1 external/libncurses
      fi
    - if [[ ! -d external/bash ]]; then
          echo -e ${cya} "Adding Bash Library..."
          git clone https://github.com/LineageOS/android_external_bash -b lineage-19.1 external/bash
      fi
    - if [[ ! -d external/lptools ]]; then
          echo -e ${cya} "Adding lptools Library..."
          git clone https://github.com/phhusson/vendor_lptools external/lptools
      fi
    - if [[ ! -z "${MAINTAINER_URL}" ]]; then
          echo -e ${cya} "Change Maintainer Profile..."
          wget "${MAINTAINER_URL}" -O "${CIRRUS_WORKING_DIR}"/maintainer.png
          cp -r "${CIRRUS_WORKING_DIR}"/maintainer.png bootable/recovery/gui/theme/portrait_hdpi/images/Default/About
      fi
    - if [[ ! -z "${KERNEL_TREE}" ]]; then
          echo -e ${cya} "Clonning Kernel Tree..."
          git clone "${KERNEL_TREE}" -b "${KERNEL_BRANCH}" "${KERNEL_PATH}"
      fi
    - if [[ ! -z "${COMMON_TREE}" ]]; then
          echo -e ${cya} "Clonning Common Tree..."
          git clone "${COMMON_TREE}" -b "${COMMON_BRANCH}" "${COMMON_PATH}"
      fi
    - if [[ ! -z "${DEVICE_TREE}" ]]; then
          echo -e ${cya} "Clonning Device Tree..."
          git clone "${DEVICE_TREE}" -b "${DEVICE_TREE_BRANCH}" "${DEVICE_PATH}"
      fi
