name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: bash ci.sh deps

    - name: Show env
      run: env
